name: Suggestion
description: Help us improve with suggestions
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion form!
  - type: input
    id: suggestion
    attributes:
      label: Link to suggestion
      description: Please share a link to your suggestion
      placeholder: https://...
    validations:
      required: true
  - type: input
    id: section
    attributes:
      label: Targeted section
      description: Please name the main section you whish your suggestion to appear in.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your suggestion
      description: How and why is your suggestion useful to this community?
      placeholder: I wish to see tool <xyz> here because it is used for ...
    validations:
      required: true
  - type: checkboxes
    id: Checklist
    attributes:
      label: Checklist
      description: |
        When filing a _suggestion_, please check the boxes below to confirm that you have:
      options:
        - label: checked if your suggestion is not already listed in __Awesome Quarto__ list.
        - label: checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections.
        - label: checked when it's a repository if it's maintained (archived repository will be rejected).
    validations:
      required: true