name: Suggestion
description: Help us improve with suggestions
labels: [suggestion]
assignees: mcanouil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion form!
  - type: input
    id: suggestion
    attributes:
      label: Link to suggestion
      description: Please share a link to your suggestion
      placeholder: https://...
    validations:
      required: true
  - type: dropdown
    id: section
    attributes:
      validations:
      required: true
      label: Targeted section
      description: Please select the section you wish your suggestion to appear in.
      multiple: false
      options:
        - label: Official documentation & quickstarts
        - label: Tutorials & workshops
        - label: Blog posts
        - label: Talks and videos
        - label: Supported editors
        - label: Libraries/Packages/Scripts
        - label: Continuous integration / Continuous deployment
        - label: Extensions
        - label: Templates/Journals
        - label: Templates/Presentations
        - label: Templates/HTML Documents
        - label: Real life examples/Presentations formats
        - label: Real life examples/Websites formats
        - label: Real life examples/Book formats
        - label: Real life examples/Other formats
        - label: Follow/Official
        - label: Follow/Community
  - type: textarea
    id: description
    attributes:
      label: Describe your suggestion
      description: How and why is your suggestion useful to this community?
      placeholder: I wish to see tool <xyz> here because it is used for ...
    validations:
      required: true
  - type: checkboxes
    id: Checklist
    attributes:
      label: Checklist
      description: |
        When filing a _suggestion_, please check the boxes below to confirm that you have:
      options:
        - label: checked if your suggestion is not already listed in __Awesome Quarto__ list.
          required: true
        - label: checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
          required: true
        - label: checked when it's a repository if it's maintained (archived repository will be rejected).
          required: true
