
name: Tweet Release

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tweet-release:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::rtweet, any::httpuv
      - name: Post Tweet
        if: github.event_name == 'release'
        shell: Rscript {0}
        run: |
          if (nzchar(Sys.getenv("RELEASE_TAG"))) {
            tag <- Sys.getenv("RELEASE_TAG")
          } else {
            tag <- gsub("-", ".", Sys.Date())
          }
          release_url <- paste0(
            "https://github.com/", Sys.getenv("GITHUB_REPOSITORY"), "/releases/tag/",
            tag
          )
          tweet_body <- sprintf(
            paste(
              "New #AwesomeQuarto release!",
              "What's new in #QuartoPub (@quarto_pub)? let's find out!",
              "Release: %s",
              "New additions: %s",
              "#RStats #Python #ObservableHQ #Julia",
              sep = "\n"
            ),
            release_url,
            "https://github.com/", Sys.getenv("GITHUB_REPOSITORY"), "#featured-new-releases"
          )
          library(rtweet)
          auth <- rtweet_bot(
            api_key = Sys.getenv("TWITTER_API_KEY"),
            api_secret = Sys.getenv("TWITTER_API_KEY_SECRET"),
            access_token = Sys.getenv("TWITTER_ACCESS_TOKEN"),
            access_secret = Sys.getenv("TWITTER_ACCESS_SECRET")
          )
          auth_as(auth)
          post_tweet(status = tweet_body)
      - name: Test Post Tweet
        if: github.event_name == 'workflow_dispatch'
        shell: Rscript {0}
        run: |
          if (nzchar(Sys.getenv("RELEASE_TAG"))) {
            tag <- Sys.getenv("RELEASE_TAG")
          } else {
            tag <- gsub("-", ".", Sys.Date())
          }
          release_url <- paste0(
            "https://github.com/", Sys.getenv("GITHUB_REPOSITORY"), "/releases/tag/",
            tag
          )
          tweet_body <- sprintf(
            paste(
              "New #AwesomeQuarto release!",
              "What's new in #QuartoPub (@quarto_pub)? let's find out!",
              "Release: %s",
              "New additions: %s",
              "#RStats #Python #ObservableHQ #Julia",
              sep = "\n"
            ),
            release_url,
            "https://github.com/", Sys.getenv("GITHUB_REPOSITORY"), "#featured-new-releases"
          )
          library(rtweet)
          auth <- rtweet_bot(
            api_key = Sys.getenv("TWITTER_API_KEY"),
            api_secret = Sys.getenv("TWITTER_API_KEY_SECRET"),
            access_token = Sys.getenv("TWITTER_ACCESS_TOKEN"),
            access_secret = Sys.getenv("TWITTER_ACCESS_SECRET")
          )
          auth_as(auth)
          post_tweet()
