
name: Tweet Item

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tweet-item:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::rtweet, any::httpuv
      - name: Post Tweet
        shell: Rscript {0}
        run: |
          readme <- readLines("README.md")
          readme <- readme[readme != ""]
          readme <- readme[-grep("^###", readme)]
          readme <- readme[-seq_len(grep("^## ", readme)[1] - 1)]
          items <- sapply(
            X = split(
              x = readme,
              f = cut(
                x = seq_along(readme),
                breaks = c(grep("^## ", readme) - 1, length(readme)),
                include.lowest = TRUE
              )
            ),
            cat = c(
              "## Tutorials & workshops",
              "## Blog posts",
              "## Talks and videos",
              "## Continuous integration / Continuous deployment",
              "## Extensions",
              "## Templates"
            ),
            FUN = function(x, cat) {
              if (!x[[1]] %in% cat) return(NULL)
              out <- x[grep("^- ", x)]
              out <- sub("^- \\[([^]]*)\\]", "'\\1' ", out)
              out <- gsub("\\[([^]]+)\\]\\([^)]+\\)", "\\1", out)
              out <- gsub(" \\(materials: [^)]+\\)| \\(slides: [^)]+\\)", "", out)
              out <- gsub("\\*", "", out)
              out <- sub(" - ", "\n", out)
              out <- sub("(\\@rladies) ", "", out, fixed = TRUE)
              out <- sub("twitter: \\", "twitter: ", out, fixed = TRUE)
              out
            }
          )
          items <- c(
            paste(
              paste("From #AwesomeQuarto:", unlist(items[!sapply(items, is.null)], use.names = FALSE)),
              "#QuartoPub #RStats #Python #ObservableHQ #JuliaLang",
              sep = "\n"
            ),
            paste(
              "Any #QuartoPub (@quarto_pub) questions/issues/ideas? There is only one place!",
              "Take a look at the Issues and Discussions, it's a gold mine of tips, tricks, hacks, solutions, and more.",
              "https://github.com/quarto-dev/quarto-cli",
              "#QuartoPub #RStats #Python #ObservableHQ #JuliaLang #AwesomeQuarto",
              sep = "\n"
            ),
            paste(
              "You saw or you made something related to #QuartoPub (@quarto_pub) either with #RStats, #Python, #ObservableHQ, or #JuliaLang?",
              "You want it to be seen/shared?",
              "Please submit a suggestion issue to #AwesomeQuarto https://github.com/mcanouil/awesome-quarto",
              "PS: if you like this list, star it and share it 😉",
              sep = "\n"
            )
          )
          item <- sample(items, 1)
          message(item)
          library(rtweet)
          auth <- rtweet_bot(
            api_key = Sys.getenv("TWITTER_API_KEY"),
            api_secret = Sys.getenv("TWITTER_API_KEY_SECRET"),
            access_token = Sys.getenv("TWITTER_ACCESS_TOKEN"),
            access_secret = Sys.getenv("TWITTER_ACCESS_SECRET")
          )
          auth_as(auth)
          i <- 0
          while(inherits(try(post_tweet(status = item), silent = TRUE), "try-error") & i < 3) i <- i +1
