
name: Tweet Release

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tweet-release:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::rtweet, any::httpuv
      - name: Test Post Tweet
        if: github.event_name == 'workflow_dispatch'
        run: Rscript .github/assets/tweet-release-test.R
      - name: Post Release Tweet thread
        if: github.event_name == 'release'
        run: Rscript .github/assets/tweet-release.R
          