
name: Tweet Release

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tweet-release:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::rtweet, any::httpuv
      - name: Test Post Tweet
        if: github.event_name == 'workflow_dispatch'
        shell: Rscript {0}
        run: |
          if (nzchar(Sys.getenv("RELEASE_TAG"))) {
            tag <- Sys.getenv("RELEASE_TAG")
          } else {
            tag <- gsub("-", ".", Sys.Date())
          }
          release_url <- paste0(
            "https://github.com/", Sys.getenv("GITHUB_REPOSITORY"), "/releases/tag/",
            tag
          )
          tweet_body <- paste(
            "New #AwesomeQuarto release!",
            "What's new in #QuartoPub (@quarto_pub)? let's find out!",
            paste("Release:", release_url),
            paste0("New additions: ", "https://github.com/", Sys.getenv("GITHUB_REPOSITORY"), "#featured-new-releases"),
            "#RStats @rstats_tweets #Python #ObservableHQ @observablehq #JuliaLang @JuliaLanguage",
            sep = "\n"
          )
          message(tweet_body)
          library(rtweet)
          auth <- rtweet_bot(
            api_key = Sys.getenv("TWITTER_API_KEY"),
            api_secret = Sys.getenv("TWITTER_API_KEY_SECRET"),
            access_token = Sys.getenv("TWITTER_ACCESS_TOKEN"),
            access_secret = Sys.getenv("TWITTER_ACCESS_SECRET")
          )
          auth_as(auth)
          post_tweet()
      - name: Post Release Tweet thread
        if: github.event_name == 'release'
        shell: Rscript {0}
        run: |
          if (nzchar(Sys.getenv("RELEASE_TAG"))) {
            tag <- Sys.getenv("RELEASE_TAG")
          } else {
            tag <- gsub("-", ".", Sys.Date())
          }
          release_url <- paste0(
            "https://github.com/", Sys.getenv("GITHUB_REPOSITORY"), "/releases/tag/",
            tag
          )
          tweet_body <- paste(
            "New #AwesomeQuarto release!",
            "What's new in #QuartoPub (@quarto_pub)? let's find out!",
            paste("Release:", release_url),
            paste0("New additions: ", "https://github.com/", Sys.getenv("GITHUB_REPOSITORY"), "#featured-new-releases"),
            "#RStats @rstats_tweets #Python #ObservableHQ @observablehq #JuliaLang @JuliaLanguage",
            sep = "\n"
          )

          readme <- readLines("README.md")
          readme <- readme[
            seq(
              grep("## Featured", readme) + 2,
              grep("^## ", readme)[grep("^## ", readme) > grep("## Featured", readme)][1] - 2
            )
          ]
          readme <- readme[readme != ""]
          readme <- readme[grep("^- ", readme)]
          readme <- sub("^- \\[([^]]*)\\]", "'\\1' ", readme)
          readme <- gsub("\\[([^]]+)\\]\\([^)]+\\)", "\\1", readme)
          readme <- gsub(" \\(materials: [^)]+\\)| \\(slides: [^)]+\\)", "", readme)
          readme <- gsub("\\*", "", readme)
          readme <- sub(" - ", "\n", readme)
          readme <- sub("twitter: \\", "twitter: ", readme, fixed = TRUE)
          items <- paste(
            paste("New in #AwesomeQuarto:", readme),
            "#QuartoPub #RStats #Python #ObservableHQ #JuliaLang",
            sep = "\n"
          )

          library(rtweet)
          auth <- rtweet_bot(
            api_key = Sys.getenv("TWITTER_API_KEY"),
            api_secret = Sys.getenv("TWITTER_API_KEY_SECRET"),
            access_token = Sys.getenv("TWITTER_ACCESS_TOKEN"),
            access_secret = Sys.getenv("TWITTER_ACCESS_SECRET")
          )
          auth_as(auth)
          post_tweet(status = tweet_body)
          reply_id <- get_my_timeline()[["id_str"]][1]
          for (item in items) {
            post_tweet(item, in_reply_to_status_id = reply_id)
          }
